require("manager-plugins.plugins-setup")
require("manager-plugins.list-plugins")

require("harvous.core.options")
require("harvous.core.keymaps")
require("harvous.core.colorscheme")
require("harvous.core.which-key")

require("harvous.syntax.autopairs")
require("harvous.syntax.rainbow2")
require("harvous.syntax.colorizer")
require("harvous.syntax.modes")
require("harvous.syntax.navigator")

require("harvous.lsp.null-ls")
require("harvous.lsp.mason")
require("harvous.lsp.lspconfig")

require("harvous.indentline")
require("harvous.neo-tree")
require("harvous.cmp")
require("harvous.telescope")
require("harvous.hlslens")
require("harvous.treesitter")
require("harvous.hop")
require("harvous.bufferline")
require("harvous.lualine")
require("harvous.toggleterm")
require("harvous.alpha-nvim")
require("harvous.noice")
require("harvous.autocommands")
require("harvous.gitsigns")
require("harvous.comment")
require("harvous.other")
